kind: Service
apiVersion: v1
metadata:
  name: acmeair
  labels:
    run: acmeair
spec:
  selector:
    run: acmeair
  ports:
    - port: 9080
      name: main
      protocol: TCP
    - port: 9443
      name: secure
      protocol: TCP
  type: NodePort
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: acmeair
  labels:
    run: acmeair
spec:
  replicas: 2
  selector:
    matchLabels:
      run: acmeair
  template:
    metadata:
      labels:
        run: acmeair
    spec:
      containers:
        - name: acmeair
          image: sppatel/acmeair-web
          imagePullPolicy: Always
          ports:
          - containerPort: 9080
          - containerPort: 9443
        - name: mongo
          image: mongo
          imagePullPolicy: Always
          ports:
          - containerPort: 27017
